"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function AccessPage() {
  const router = useRouter();
  const [isPopupOpen, setIsPopupOpen] = useState(false);
  const [nextPageUrl, setNextPageUrl] = useState("");
  const [hasConsented, setHasConsented] = useState(false);

  const handleActionClick = (url: string) => {
    setNextPageUrl(url);
    setHasConsented(false);
    setIsPopupOpen(true);
  };

  const handleProceed = () => {
    if (hasConsented && nextPageUrl) {
      router.push(nextPageUrl);
    }
  };

  const disclaimerData = [
    {
      title: "⚠️ 1. No Patient Data Allowed",
      description:
        "Users must not enter, upload, or store any patient-identifiable information anywhere within the application, including notes, comments, saved text, or custom repertory entries. This platform is not designed, certified, or intended for storing or processing patient health information.",
    },
    {
      title: "⚠️ 2. Data Storage & Responsibility",
      description:
        "The web application stores only user notes (if followed according to protocols laid in this disclaimer) but does not store user-generated repertory tables/sheets. Users are solely responsible for saving or exporting their work externally. Homeosetu Software LLP is not liable for any data loss, corruption, or failure to save work.",
    },
    {
      title: "⚠️ 3. Trial Access & Account Integrity",
      description:
        "Trial access is strictly limited to one individual per account. Creating multiple accounts, sharing login credentials, or attempting to bypass access controls may result in immediate suspension.",
    },
    {
      title: "⚠️ 4. Educational Use Only",
      description:
        "The website www.homeosetu.com and all content of Homeosetu Software LLP is an educational and reference tool. It is not a substitute for clinical judgment, diagnosis, or treatment planning. Repertory data and suggestions are provided for reference purposes only.",
    },
    {
      title: "⚠️ 5. No Medical Advice",
      description:
        "All content, suggestions, and responses generated by Homeosetu Software LLP are intended solely for general educational and informational purposes. They do not constitute medical advice, diagnosis, prescription, or treatment. Users must consult qualified healthcare professionals for all medical decisions.",
    },
    {
      title: "⚠️ 6. Not for Unsupervised Layperson Use",
      description:
        "The platform is designed for trained practitioners and supervised patient education. Laypersons must not act on any information provided without consulting a licensed medical professional. Do not delay or disregard professional medical advice based on platform content.",
    },
    {
      title: "⚠️ 7. No Practitioner–Patient Relationship",
      description:
        "Use of this platform does not establish any physician-patient or practitioner-patient relationship. All content is intended to assist not replace personal medical examination, diagnosis, or treatment planning by qualified professionals.",
    },
    {
      title: "⚠️ 8. Outcome Variability",
      description:
        "Any clinical suggestion or protocol may vary in effectiveness depending on diagnosis accuracy, case history, constitution, comorbidities, and practitioner judgment. Homeosetu Software LLP does not guarantee outcomes and assumes no responsibility for clinical decisions made using its content.",
    },
    {
      title: "⚠️ 9. Liability Limitation",
      description:
        "Homeosetu Software LLP, its website creators, and contributors disclaim all liability for any direct or indirect loss, harm, or risk arising from use of the platform, including but not limited to clinical, financial, operational, or reputational outcomes. Users must independently verify all clinical information.",
    },
    {
      title: "⚠️ 10. Protocol Attribution",
      description:
        "Homeosetu Software LLP does not claim ownership, license, or endorsement of any third-party protocols unless explicitly stated. References to external protocols are for educational comparison only and do not imply affiliation or authorization.",
    },
    {
      title: "⚠️ 11. Privacy & Security Disclaimer",
      description:
        "While Homeosetu Software LLP follows reasonable digital security practices, it does not guarantee absolute protection against unauthorized access, breaches, or data interception. Users are responsible for maintaining the confidentiality of their login credentials.",
    },
    {
      title: "⚠️ Regulatory Compliance Disclaimer",
      description:
        "Use of this platform must comply with applicable laws, including:<br/><br/>• National Commission for Homoeopathy (NCH) guidelines<br/>• Digital Personal Data Protection Act (DPDP)<br/>• Local clinical practice regulations<br/><br/>Users are responsible for ensuring compliance with professional, ethical, and legal standards.",
    },
  ];
  return (
    <div className="min-h-[calc(100vh-100px)] py-12 flex flex-col items-center justify-center bg-slate-50 px-4 relative">
      {/* Cards Container */}
      <div className="flex flex-col md:flex-row gap-6 items-stretch justify-center w-full max-w-5xl mx-auto animate-in fade-in zoom-in-95 duration-200">
        {/* Free Trial Card */}
        <div className="w-full md:flex-1 max-w-md mx-auto rounded-3xl bg-white border border-slate-200 shadow-lg hover:shadow-xl transition-shadow duration-300 overflow-hidden flex flex-col relative">
          <div className="p-8 pb-6 flex-1">
            <span className="inline-block py-1.5 px-3 rounded-full bg-emerald-100 text-emerald-700 text-[11px] font-bold tracking-wider uppercase mb-5">
              Free Trial
            </span>

            <div className="mb-2">
              <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">
                ₹0{" "}
                <span className="text-xl font-semibold text-slate-400">
                  / 9 days
                </span>
              </h2>
            </div>
            <p className="text-sm font-semibold text-emerald-500 mb-6 flex items-center gap-1.5">
              <svg
                className="w-4 h-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              No credit card required
            </p>

            <p className="text-sm text-slate-600 leading-relaxed mb-8">
              Start Your{" "}
              <strong className="text-slate-900 font-bold">
                Homeosetu Webapp
              </strong>{" "}
              9-Day Free Trial. Explore the app before you commit.
            </p>

            <div className="border-t border-slate-100 pt-8">
              <strong className="text-slate-900 block font-bold mb-5 text-[15px]">
                Preview the core toolkit:
              </strong>
              <ul className="space-y-4">
                {[
                  "Kent Repertory With Patient Versions and when to use each Mind rubric.",
                  "Homeosetu Clinical Repertory(clinical conditions from Clarke,Boericke,Hempel,Pulte,Hering with Homeosetu Lens).",
                  "Homeosetu Bowel Nosodes Repertory.",
                  "Allen's Fever Repertory.",
                  "Homeosetu Repertory to Keynotes &amp; Characteristics (preview mode).",
                  "HomeoSetu Lens previews on rubrics &amp; each remedy.",
                  "Try <strong class='font-semibold text-slate-800'>Homeosetu</strong> Intelligence Clinic Assistant for quick replies.",
                  "Try before you subscribe.",
                  "“Start using our WebApp… and use the trial for 9 days.”",
                ].map((item, idx) => (
                  <li
                    key={idx}
                    className="flex items-start text-[14px] text-slate-600"
                  >
                    <div className="mt-2 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-emerald-500 mr-3.5"></div>
                    <span
                      dangerouslySetInnerHTML={{ __html: item }}
                      className="leading-relaxed"
                    />
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="p-8 pt-6 mt-auto bg-slate-50 border-t border-slate-100 flex flex-col gap-4">
            <div className="text-[13px] text-slate-500 leading-relaxed">
              <strong className="text-slate-700 block mb-1">
                Start Free Trial
              </strong>
              Trial lasts 9 days. Post‑trial, onboarding charges apply.
            </div>

            <button
              onClick={() => handleActionClick("/software/kent-repertory")}
              className="w-full py-4 px-4 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white font-bold text-[15px] shadow-md hover:shadow-lg transition-all transform hover:-translate-y-0.5"
            >
              Start Free Trial
            </button>

            <div className="text-center text-xs text-slate-400 font-medium mt-2">
              Tutorials on YouTube • Built for the Everyday Homeopath
            </div>
          </div>
        </div>

        {/* Premium Popup Card */}
        <div className="w-full md:flex-1 max-w-md mx-auto rounded-3xl bg-white border border-slate-200 shadow-xl hover:shadow-2xl transition-shadow duration-300 overflow-hidden flex flex-col relative">
          <div className="p-8 pb-6 flex-1">
            <span className="inline-block py-1.5 px-3 rounded-full bg-indigo-100 text-indigo-700 text-[11px] font-bold tracking-wider uppercase mb-5">
              Full Access
            </span>

            <div className="mb-2 flex flex-col gap-1">
              <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">
                ₹499{" "}
                <span className="text-xl font-semibold text-slate-400">
                  / mo
                </span>{" "}
                <span className="text-sm font-medium text-slate-400">(IN)</span>
              </h2>
              <h3 className="text-xl font-bold text-slate-600 mt-1">
                $25{" "}
                <span className="text-sm font-medium text-slate-400">
                  / mo (Global)
                </span>
              </h3>
            </div>
            <p className="text-sm font-semibold text-indigo-500 mb-6 flex items-center gap-1.5">
              <svg
                className="w-4 h-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
                />
              </svg>
              Cancel anytime
            </p>

            <p className="text-sm text-slate-600 leading-relaxed mb-8">
              Start Your{" "}
              <strong className="text-slate-900 font-bold">
                HomeoSetu WebApp Monthly Subscription.
              </strong>{" "}
              Unlock all books, tools, and weekly enhancements.
            </p>

            <div className="border-t border-slate-100 pt-8">
              <strong className="text-slate-900 block font-bold mb-5 text-[15px]">
                Full access to everything:
              </strong>
              <ul className="space-y-4">
                {[
                  "All 5 repertories fully unlocked",
                  "Meanings under each rubric in mind section of Kent Repertory",
                  "Patient versions &amp; When to use which Rubric.",
                  "Add notes in each rubric &amp; search your own patient language in rubrics.",
                  "Full <strong class='font-semibold text-slate-800'>HomeoSetu</strong> Lens across Clinical repertory &amp; Keynotes to MM.",
                  "<strong class='font-semibold text-slate-800'>Homeosetu</strong> Intelligence Clinic Assistant: diagnosis aid, remedy relationships, validation tools",
                  "Weekly updates + expanding repertories.",
                  "Coming Soon Mobile App which will seamlessly integrate with WebApp",
                  "“Repertories… are actively being expanded by our team on a daily basis.”",
                ].map((item, idx) => (
                  <li
                    key={idx}
                    className="flex items-start text-[14px] text-slate-600"
                  >
                    <div className="mt-2 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-indigo-500 mr-3.5"></div>
                    <span
                      dangerouslySetInnerHTML={{ __html: item }}
                      className="leading-relaxed"
                    />
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="p-8 pt-6 mt-auto bg-slate-50 border-t border-slate-100 flex flex-col gap-4">
            <div className="text-[13px] text-slate-500 leading-relaxed">
              <strong className="text-slate-700 block mb-1">
                Subscribe Monthly
              </strong>
              Cancel anytime. Billed monthly.
            </div>

            <button
              onClick={() => handleActionClick("/checkout?type=kent-access")}
              className="w-full py-4 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-[15px] shadow-md hover:shadow-xl transition-all transform hover:-translate-y-0.5"
            >
              Pay for Access
            </button>

            <div className="text-center text-xs text-slate-400 font-medium mt-2">
              Tutorials on YouTube • Built for the Everyday Homeopath
            </div>
          </div>
        </div>
      </div>

      {isPopupOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[75vh]">
            <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50">
              <h3 className="text-xl font-bold text-slate-900">
                Homeosetu WebApp Disclaimer
              </h3>
              <button
                onClick={() => setIsPopupOpen(false)}
                className="text-slate-400 hover:text-slate-600 transition-colors"
              >
                <svg
                  className="w-5 h-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>

            <div className="p-6 overflow-y-auto">
              <div className="text-sm text-slate-600 space-y-4">
                <p>
                  Please review and agree to the following terms before
                  proceeding:
                </p>
                <div className="space-y-6 mt-4">
                  {disclaimerData.map((item, index) => (
                    <div key={index} className="flex gap-4">
                      <div className="shrink-0 flex items-center justify-center w-7 h-7 rounded-full bg-indigo-50 text-indigo-600 text-[13px] font-bold mt-0.5 ring-4 ring-indigo-50/50">
                        {index + 1}
                      </div>
                      <div className="space-y-1.5 text-slate-600 pb-4 border-b border-slate-100 last:border-0 last:pb-0 w-full">
                        <h3 className="font-semibold text-slate-800 text-[15px]">
                          {item.title}
                        </h3>
                        <p
                          className="leading-relaxed"
                          dangerouslySetInnerHTML={{ __html: item.description }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="p-6 border-t border-slate-100 bg-slate-50 flex flex-col gap-4">
              <label className="flex items-start gap-3 cursor-pointer group">
                <div className="relative flex items-center justify-center mt-0.5">
                  <input
                    type="checkbox"
                    className="w-5 h-5 border-2 border-slate-300 rounded peer checked:bg-indigo-500 checked:border-indigo-500 transition-colors cursor-pointer appearance-none"
                    checked={hasConsented}
                    onChange={(e) => setHasConsented(e.target.checked)}
                  />
                  <svg
                    className="absolute w-3 h-3 text-white pointer-events-none opacity-0 peer-checked:opacity-100 transition-opacity"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={3}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M5 13l4 4L19 7"
                    />
                  </svg>
                </div>
                <span className="text-sm text-slate-700 font-medium group-hover:text-slate-900 transition-colors">
                  By proceeding, you acknowledge that you have read, understood,
                  and agree to all the above disclaimers. You accept full
                  responsibility for how you use the platform and the
                  information it provides.
                </span>
              </label>

              <div className="flex justify-end gap-3 mt-2">
                <button
                  onClick={() => setIsPopupOpen(false)}
                  className="px-5 py-2.5 rounded-xl text-slate-600 font-medium hover:bg-slate-200 transition-colors text-sm"
                >
                  Cancel
                </button>
                <button
                  onClick={handleProceed}
                  disabled={!hasConsented}
                  className="px-5 py-2.5 rounded-xl bg-indigo-500 hover:bg-indigo-600 disabled:bg-slate-300 disabled:cursor-not-allowed text-white font-semibold transition-colors text-sm"
                >
                  Proceed
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
