/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jyyHAlJ8VsI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Announcements() {
  return (
    <div className="fixed bottom-0 left-0 z-50 w-full bg-primary text-primary-foreground py-2">
      <div className="container mx-auto flex justify-center px-4">
        <p className="text-xs font-medium">
          Announcement - New courses releasing soon 🎉
        </p>
      </div>
    </div>
  )
}
