export type Remedy = {
  abbr: string
  grade: number
}

export type Note = {
  type: "system" | "user"
  source?: string
  text: string
}

export type CrossReference = {
  chapter: string
  rubric: string
}

export type Rubric = {
  id: string
  name: string
  remedies: Remedy[]
  meaning?: string
  notes: Note[]
  crossReferences?: CrossReference[]
}

export type Chapter = {
  id: string
  name: string
  icon: string
  description?: string
  rubrics: Rubric[]
}

export type KentRepertory = {
  bookName: string
  chapters: Chapter[]
}

export const REPERTORY_BOOKS: KentRepertory[] = []

export const REMEDY_DICTIONARY: Record<string, string> = {
  "abies-c.": "Abies canadensis",
  "abies-n.": "Abies nigra",
  "abrot.": "Abrotanum",
  "absin.": "Absinthium",
  "acal.": "Acalypha indica",
  "acet-ac.": "Acetic acid",
  "acon-c.": "Aconitum cammarum",
  "acon.": "Aconitum napellus",
  "acon-f.": "Aconitum ferox",
  "acon-l.": "Aconitum lycotonum",
  "act-sp.": "Actaea spicata",
  "adren.": "Adrenalin",
  "aesc.": "Aesculus hippocastanum",
  "aesc-g.": "Aesculus glabra",
  "aeth.": "Aethusa cynapium",
  "agar-em.": "Agaricus emeticus",
  "agar.": "Agaricus muscarius",
  "agar-ph.": "Agaricus phalloides",
  "agn.": "Agnus castus",
  "agra-n.": "Agraphis nutans",
  "ail.": "Ailanthus",
  "alco.": "Alcohol",
  "alet.": "Aletris farinosa",
  "all-c.": "Allium сера",
  "all-s.": "Allium sativum",
  "aloe.": "Aloe socotrina",
  "alst.": "Alstonia constricta",
  "alumn.": "Alumen",
  "alum.": "Alumina",
  "alum-sil.": "Alumina silicata",
  "ambr.": "Ambra grisea",
  "ambro.": "Ambrosia artemisiæ folia",
  "ammc.": "Ammoniacum gummi",
  "am-be.": "Ammonium benzoicum",
  "am-br.": "Ammonium bromatum",
  "am-c.": "Ammonium carbonicum",
  "am-caust.": "Ammonium causticum",
  "am-m.": "Ammonium muriaticum",
  "amph.": "Amphisbæna",
  "amyg.": "Amygdalæ amaræ aqua",
  "aml-n.": "Amyl nitrite",
  "anac.": "Anacardium orientale",
  "anac-oc.": "Anacardium occidentale",
  "anag.": "Anagallis arvensis",
  "anan.": "Anantherum muricatum",
  "ang.": "Angustura vera",
  "anil.": "Anilinum",
  "anis.": "Anisum stellatum",
  "anth.": "Anthemis nobilis",
  "anthr.": "Anthracinum",
  "anthro.": "Anthrokokali",
  "ant-a.": "Antimonium arsenicosum",
  "ant-c.": "Antimonium crudum",
  "ant-chl.": "Antimonium chloridum",
  "ant-ox.": "Antimonium oxydatum",
  "ant-s.": "Antimonium sulph. auratum",
  "ant-t.": "Antimonium tartaricum",
  "aphis.": "Aphis chenopodii glauci",
  "apis.": "Apis mellifica",
  "ap-g.": "Apium graveolens",
  "арос.": "Аросуnum cannabinum",
  "арос-а.": "Ароcynum androsæmifolium",
  "apom.": "Apomorphium",
  "aral.": "Aralia racemosa",

  "aran.": "Aranea diadema",
  "aran-s.": "Aranea scinencia",
  "arg-c.": "Argentum cyanidum",
  "arg.": "Argentum metallicum",
  "arg-mur.": "Argentum muriaticum",
  "arg-n.": "Argentum nitricum",
  "arn.": "Arnica montana",
  "ars.": "Arsenicum album",
  "ars-h.": "Arsenicum hydrogenisatum",
  "ars-i.": "Arsenicum iodatum",
  "ars-m.": "Arsenicum metallicum",
  "ars-s-f.": "Arsenicum sulphuratum flavum",
  "ars-s-r.": "Arsenicum sulphuratum rubrum",
  "art-v.": "Artemesia vulgaris",
  "arum-d.": "Arum dracontium",
  "arum-i.": "Arum italicum",
  "arum-m.": "Arum maculatum",
  "arum-t.": "Arum triphyllum",
  "arund.": "Arundo mauritanica",
  "arund-d.": "Arundo donax",
  "asaf.": "Asafœtida",
  "asar.": "Asarum europæum",
  "asc-c.": "Asclepias cornuti",
  "asc-t.": "Asclepias tuberosa",
  "asim.": "Asimina triloba",
  "aspar.": "Asparagus officinalis",
  "astac.": "Astacus fluviatilis",
  "aster.": "Asterias rubens",
  "atro.": "Atropinum",
  "atro-s.": "Atropia sulphurica",
  "aur.": "Aurum metallicum",
  "aur-a.": "Aurum arsenicum",
  "aur-i.": "Aurum iodatum",
  "aur-m.": "Aurum muriaticum",
  "aur-m-n.": "Aurum muriaticum natronatum",
  "aur-s.": "Aurum sulphuratum",
  "bac-b.": "Bacillinum Burnett",
  "bac-dys.": "Bacillus Dysentrico, Dysentery Bacillus, Shigella Dysentriae",
  "bac-faec.": "Bacillus Faecalis",
  "bac-morg.": "Morgan Pure, Morgan bacillus, Morgan pure, Proteus morgani",
  "bac-morg-b.": "Morgan Bach",
  "bac-morg-g.": "Morgan Gaertner",
  "bac-mut.": "Bacillus Mutabile. Mutabile Bach",
  "bac-prot.": "Bacillus Proteus",
  "bac-sev.": "Bacillus Seven",
  "bac-syco.": "Sycotic co. bacillus. Sycotic bacillus. Bowel nosode",
  "bac-ten.": "Bacillus ten",
  "bad.": "Badiaga",
  "bals.": "Balsamum peruvianum",
  "bapt.": "Baptisia tinctoria",
  "bart.": "Bartfelder (acid spring)",
  "bar-ac.": "Baryta acetica",
  "bar-c.": "Baryta carbonica",
  "bar-i.": "Baryta iodata",
  "bar-m.": "Baryta muriatica",
  "bell.": "Belladonna",
  "bell-p.": "Bellis perennis",
  "benz.": "Benzinum",
  "benz-ac.": "Benzoic acid",
  "benz-n.": "Benzinum nitricum",
  "berb.": "Berberis vulgaris",
  "berb-aq.": "Berberis Aquifolium",
  "bism.": "Bismuthum oxidum",
  "blatta-a.": "Blatta americana",
  "blatta.": "Blatta orientalis",
  "bol.": "Boletus laricis",
  "bor-ac.": "Boracicum acidum",
  "borx.": "Borax",
  "both.": "Bothrops lanceolatus",
  "bov.": "Bovista",
  "brach.": "Brachyglottis repens",
  "brom.": "Bromium",
  "bruc.": "Brucea antidysenterica",
  "bry.": "Bryonia alba",
  "bufo.": "Bufo rana",
  "buf-s.": "Bufo sahytiensis",
  "cact.": "Cactus grandiflorus",
  "cadm.": "Cadmium sulphuratum",
  "cahin.": "Cahinca",
  "cain.": "Cainca",
  "caj.": "Cajuputum",
  "calad.": "Caladium seguinum",
  "calc-ac.": "Calcarea acetica",
  "calc-ar.": "Calcarea arsenica",
  "calc.": "Calc.,Bac., -Abdomen, DISTENDED: In fat scrofulous children, Calc. 6, 6h. Intercurrently, Bac 30, once a week.",
  "calc-caust.": "Calcarea caustica",
  "calc-chlor.": "Calcarea Chlorinata",
  "calc-f.": "Calcarea fluorata",
  "calc-i.": "Calcarea iodata",
  "calc-m.": "Calcarea Muriaticum",
  "calc-p.": "Calcarea phosphorica",
  "calc-sil.": "Calcarea silicata",
  "calc-s.": "Calcarea sulphurica",
  "calen.": "Calendula officinalis",
  "calli.": "Calliandra houstoni",
  "calo.": "Calotropis gigantea",
  "calt.": "Caltha palustris",
  "camph.": "Camphora officinarum",
  "canch.": "Canchalagua",
  "cann-i.": "Cannabis indica",
  "cann-s.": "Cannabis sativa",
  "canth.": "Cantharis",
  "caps.": "Capsicum",
  "carb-ac.": "Carbolic acid",
  "carb-an.": "Carbo animalis",
  "carb-h.": "Carboneum hydrogenisatun",
  "carbo-o.": "Carboneum oxygenisatum",
  "carb-s.": "Carboneum sulphuratum",
  "carb-v.": "Carbo vegetabilis",
  "card-b.": "Carduus benedictus",
  "card-m.": "Carduus marianus",
  "carl.": "Carlsbad",
  "casc.": "Cascarilla",
  "cast-v.": "Castanea vesca",
  "cast-eq.": "Castor equi",
  "cast.": "Castoreum",
  "caul.": "Caulophyllum thalictroides",
  "caust.": "Causticum",
  "cean.": "Ceanothus americanus",
  "cedr.": "Cedron",
  "cench.": "Cenchris contortrix",
  "cent.": "Centaurea tagana",
  "cere-b.": "Cereus bonplandii",
  "cer-s.": "Cereus serpentaria",
  "cet.": "Cetrararia islandica",
  "cham.": "Chamomilla",
  "chel.": "Chelidonium majus",
  "chen.": "Chenopodium glauci aphis",
  "chen-a.": "Chenopodium anthelminticum",
  "chen-v.": "Chenopodium vulvaria",
  "chim.": "Chimaphila umbellata",
  "chim-m.": "Chimaphila maculata",
  "chin.": "China officinalis",
  "chin-a.": "Chininum arsenicosum",
  "chin-b.": "Chininum brom",
  "chin-s.": "Chininum sulphuricum",
  "chion.": "Chionanthus virginica",
  "chlol.": "Chloralum",
  "chlf.": "Chloroform",
  "chlor.": "Chlorum",
  "chol.": "Cholesterinum",
  "chr-as.": "Chromicum acidum",
  "chr-ox.": "Chromicum oxydatum",
  "cic.": "Cicuta virosa",
  "cimx.": "Cimex",
  "cimic.": "Cimicifuga racemosa (Actaea Racemosa)",
  "cin.":"Cin. -Abdomen, DISTENDED: When due to worms, Cina 3, 6h.",
  "cina": "Cina",
  "cinch.": "Cinchonium sulphuricum",
  "cinch-b.": "Cinchona boliviana",
  "cinnb.": "Cinnabaris",
  "cinnm.": "Cinnamomum",
  "cine-m.": "Cineraria Maritima",
  "cist.": "Cistus canadensis",
  "cit-ac.": "Citric acid",
  "cit-l.": "Citrus limonum",
  "cit-v.": "Citrus vulgaris",
  "clem.": "Clematis erecta",
  "cob.": "Cobaltum",
  "coca.": "Coca",
  "cocaine.": "Cocainum muriaticum",
  "cocc.": "Cocculus indicus",
  "cocc-s.": "Coccinella septempunctata",
  "coc-c.": "Coccus cacti",
  "coch.": "Cochlearia armoracia",
  "cod.": "Codeinum",
  "coff.": "Coffea cruda",
  "coff-t.": "Coffea tosta",
  "colch.": "Colchicum autumnale",
  "coll.": "Collinsonia canadensis",
  "coloc.": "Colocynthis",
  "colos.": "Colostrum",
  "com.": "Comocladia dentata",
  "con.": "Conium maculatum",
  "conch.": "Conchiolinum",
  "conv.": "Convallaria majalis",
  "conv-d.": "Convolvulus duartinus",
  "cop.": "Copaiva officinalis",
  "cor-r.": "Corallium rubrum",
  "cori-r.": "Coriaria ruscifolia",
  "corn.": "Cornus circinata",
  "corn-f.": "Cornus florida",
  "corn-s.": "Cornus seriea",
  "crat.": "Crategus Oxycantha",
  "croc.": "Crocus sativus",
  "cot.": "Cotyledon umbilicus",
  "crot-c.": "Crotalus cascavella",
  "crot-h.": "Crotalus horridus",
  "crot-t.": "Croton tiglium",
  "cub.": "Cubeba officinalis",
  "culx.": "Culex muscæ",
  "cund.": "Cundurango",
  "cupr.": "Cuprum metallicum",
  "cupr-a.": "Cuprum aceticum",
  "cupr-ar.": "Cuprum arsenicosum",
  "cupr-n.": "Cuprum nitricum",
  "cupr-s.": "Cuprum sulphuricum",
  "cur.": "Curare",
  "cycl.": "Cyclamen europæum",
  "cypr.": "Cypripedium pubescens",
  "daph.": "Daphne indica",
  "der.": "Derris pinnata",
  "dig.": "Digitalis purpurea",
  "dios.": "Dios. -Abdomen, DISTENDED: If from flatulence, with great pain, the bowels being open or loose, Dios. 12, 6h.",
  "diph.": "Diptherinum",
  "dirc.": "Dirca palustris",
  "dol.": "Dolichos pruriens",
  "dor.": "Doryphora",
  "dros.": "Drosera rotundifolia",
  "dub.": "Duboisinum",
  "dulc.": "Dulcamara",
  "echi.": "Echinacea angustifolia",
  "elaps.": "Elaps corallinus",
  "elat.": "Elaterium",
  "electr.": "Electricitas",
  "epig.": "Epigea repens",
  "equis.": "Equisetum hyemale",
  "erechthites.": "Erechthites hieracifolia",
  "erig.": "Erigeron canadense",
  "ery-a.": "Eryngium aquaticum",
  "ether.": "Ether",
  "eucal.": "Eucalyptus globulus",
  "eug.": "Eugenia jambos",
  "euon.": "Euonymus europæus",
  "eup-per.": "Eupatorium perfoliatum",
  "eup-pur.": "Eupatorium purpureum",
  "euph.": "Euphorbium",
  "euph-amyg.": "Euphorbia amygdaloides",
  "euph-het.": "Euphorbia heterodoxa",
  "euphr.": "Euphrasia officinalis",
  "eupi.": "Eupion",
  "fago.": "Fagopyrum",
  "ferr-ar.": "Ferrum arsenicosum",
  "ferr.": "Ferrum metallicum",
  "ferr-ac.": "Ferrum aceticum",
  "ferr-i.": "Ferrum iodatum",
  "ferr-ma.": "Ferrum magneticum",
  "ferr-m.": "Ferrum muriaticum",
  "ferr-p.": "Ferrum phosphoricum",
  "ferr-pic.": "Ferrum picricum",
  "ferr-py.": "Ferrum Pyrophosphoricum",
  "ferr-s.": "Ferrum sulphuricum",
  "fil.": "Filix mas",
  "fl-ac.": "Fluoricum acidum",
  "form.": "Formica rufa",
  "frag-v.": "Fragaria vesca",
  "gad.": "Gadus morrhua",
  "gali.": "Galium Aparine",
  "gall-ac.": "Gallicum acidum",
  "gamb.": "Gambogia",
  "gels.": "Gelsemium sempervirens",
  "genist.": "Genista tinctoria",
  "gent-l.": "Gentiana lutea",
  "gent-c.": "Gentiana cruciata",
  "ger.": "Geranium maculatum",
  "get.": "Gettisburg water",
  "gins.": "Ginseng",
  "gland.": "Glanderine",
  "glon.": "Glonoin",
  "gnaph.": "Gnaphalium",
  "goss.": "Gossypium herbaceum",
  "gran.": "Granatum punica",
  "graph.": "Graphites",
  "grat.": "Gratiola officinalis",
  "grin.": "Grindelia robusta",
  "gua.": "Guaco",
  "guano.": "Guano aust",
  "guar.": "Guarana",
  "guare.": "Guarea",
  "guaj.": "Guaiacum",
  "gunp.": "Gunpowder",
  "gymn.": "Gymnocladus",
  "haem.": "Hæmatoxylon",
  "ham.": "Hamamelis virginica",
  "hecla.": "Hecla lava",
  "hedeom.": "Hedeoma pulegioides",
  "hell.": "Helleborus niger",
  "helo.": "Heloderma",
  "helon.": "Helonias dioica",
  "hep.": "Hepar sulphuris calcareum",
  "hipp.": "Hippomanes",
  "hippoz.": "Hippozaenium",
  "hir-m.": "Hirudo Medicinalis (sanguisuga)",
  "hom.": "Homarus",
  "hura.": "Hura braziliensis",
  "hydrang.": "Hydrangea arborescens",
  "hydr.": "Hydrastis canadensis",
  "hydro.": "Hydrocotyle asiatica",
  "hydr-ac.": "Hydrocyanic acid",
  "hyos.": "Hyoscyamus niger",
  "hyper.": "Hypericum perforatum",
  "iber.": "Iberís amara",
  "ictod.": "Ictodes fœtida",
  "ign.": "Ign., Asaf., -Abdomen, DISTENDED:Hysterical distension, (1) Ign. 12, 2h. (2) Asaf. 12, 2h.",
  "iii.": "Illicium anisatum",
  "indg.": "Indigo",
  "ind.": "Indium metallicum",
  "ing.": "Ingluvin",
  "inul.": "Inula helenium",
  "iodof.": "Iodoformum",
  "iod.": "Iodium",
  "ip.": "Ipecacuanha",
  "ipom.": "Ipomia purpurea",
  "irid.": "Iridium metallicum",
  "ir-fl.": "Iris florentina",
  "ir-fœ.": "Iris fœtidissima",
  "ir-g.": "Iris germanica",
  "iris-t.": "Iris Tenax",
  "iris.": "Iris versicolor",
  "jab.": "Jaborandi",
  "jac.": "Jacaranda gualandai",
  "jac-c.": "Jacaranda caroba",
  "jal.": "Jalapa",
  "jatr.": "Jatropha curcas",
  "jug-c.": "Juglans cinerea",
  "jug-r.": "Juglans regia",
  "junc.": "Juncus effusus",
  "juni.": "Juniperus virginiana",
  "kali-a.": "Kali aceticum",
  "kali-ar.": "Kali arsenicosum",
  "kali-bi.": "Kali bichromicum",
  "kali-br.": "Kali bromatum",
  "kali-c.": "Kali carbonicum",
  "kali-chl.": "Kali chloricum",
  "kali-cit.": "kali citricum",
  "kali-cy.": "Kali cyanatum",
  "kali-fer.": "Kali ferrocyanicum",
  "kali-i.": "Kali iodatum",
  "kali-m.": "Kali muriaticum",
  "kali-ma.": "Kali manganicum",
  "kali-n.": "Kali nitricum",
  "kali-ox.": "Kali oxalicum",
  "kali-p.": "Kali phosphoricum",
  "kali-pic.": "Kali picricum",
  "kali-s.": "Kali sulphuricum",
  "kalm.": "Kalmia latifolia",
  "kaol.": "Kaolin",
  "kino": "Kino",
  "kiss.": "Kissengen",
  "kreos.": "Kreosotum",
  "lac-c.": "Lac caninum",
  "lac-d.": "Lac defloratum",
  "lac-f.": "Lac felinum",
  "lac-v.": "Lac Vaccinum",
  "lach.": "Lachesis",
  "lachn.": "Lachnanthes tinctoria",
  "lac-ac.": "Lactic acid",
  "lact.": "Lactuca virosa",
  "lam.": "Lamium album",
  "lap-a.": "Lapis albus",
  "lappa-a.": "Lappa arctium",
  "lappa-m.": "Lappa major",
  "lath.": "Lathyrus sativus",
  "lat-m.": "Latrodectus mactans",
  "laur.": "Laurocerasus",
  "lec.": "Lecithin",
  "led.": "Ledum palustre",
  "lem-m.": "Lemna minor",
  "lepi.": "Lepidium bonariense",
  "lept.": "Leptandra virginica",
  "lil-t.": "Lilium tigrinum",
  "linu-c.": "Linum cathar",
  "lith.": "Lithium carbonicum",
  "lith-m.": "Lithium muriaticum",
  "lob-c.": "Lobelia cardinalis",
  "lob.": "Lobelia inflata",
  "lob-e.": "Lobelia Erinus",
  "lob-s.": "Lobelia syphilitica",
  "lup.": "Lupulus",
  "lyc.": "Lyc., -Abdomen, DISTENDED: If due to flatulence with or without constipation, Lyc. 6, 6hrly",
  "lycpr.": "Lycopersicum",
  "lycps.": "Lycopus virginicus",
  "lyss.": "Hydrophobinum or lyssinum",
  "mag-arct.": "Magnetis polus arcticus",
  "mag-aust.": "Magnetis polus australis",
  "mag-c.": "Magnesia carbonica",
  "mag-m.": "Magnesia muriatica",
  "mag-p.": "Magnesia phosphorica",
  "mag-p-a.": "Magnetis poli ambo",
  "mag-s.": "Magnesia sulphurica",
  "maland.": "Malandrinum",
  "malar.": "Malaria officinalis",
  "manc.": "Mancinella (Hippomane mancinella)",
  "mang.": "Manganum",
  "mang-m.": "Manganum muriaticum",
  "med.": "Medorrhinum",
  "meli.": "Melilotus alba",
  "menis.": "Menispermum",
  "ment.": "Mentha piperita",
  "meny.": "Menyanthes",
  "meph.": "Mephitis",
  "merc.": "Mercurius Solubilis hahnemaanian",
  "merc-v.": "Mercurius vivus",
  "merc-ac.": "Mercurius aceticus",
  "merc-c.": "Mercurius corrosivus",
  "merc-cy.": "Mercurius cyanatus",
  "merc-d.": "Mercurius dulcis",
  "merc-i-f.": "Mercurius iodatus flavus",
  "merc-i-r.": "Mercurius iodatus ruber",
  "merc-n.": "Mercurius nitrosus",
  "merc-p-r.": "Mercurius præcipitatus ruber",
  "merc-sul.": "Mercurius sulphuricus",
  "merl.": "Mercurialis perennis",
  "mez.": "Mezereum",
  "mill.": "Millefolium",
  "mit.": "Mitchella repens",
  "morph.": "Morphinum",
  "mosch.": "Moschus",
  "murx.": "Murex",
  "mur-ac.": "Muriaticum acidum",
  "mygal.": "Mygale lasiodora",
  "myos.": "Myosotis",
  "myric.": "Myrica cerifera",
  "myris.": "Myristica sebifera",
  "myrt-c.": "Myrtus communis",
  "naja": "Naja tripudia",
  "naph.": "Naphthalin",
  "narcot.": "Narcotinum",
  "nat-ac.": "Natrum aceticum",
  "nat-a.": "Natrum arsenicatum",
  "nat-c.": "Natrum carbonicum",
  "nat-caco.": "Natrum Cacodilinum",
  "nat-h.": "Natrum hypochlorosum",
  "nat-m.": "Natrum muriaticum",
  "nat-n.": "Natrum nitricum",
  "nat-p.": "Natrum phosphoricum",
  "nat-s.": "Natrum sulphuricum",
  "nicc.": "Niccolum",
  "nicc-s.": "Niccolum sulph",
  "nit-ac.": "Nitricum acidum",
  "nit-m-ac.": "Nitro muriatic acid",
  "nit-s-d.": "Nitri spiritus dulcis",
  "nitro-o.": "Nitrogenum oxygenatum",
  "nuph.": "Nuphar luteum",
  "nux-m.": "Nux moschata",
  "nux-j.": "Nux juglans",
  "nux-v.": "Nux vomica",
  "nym.": "Nymphæa odorata",
  "oci.": "Ocimum canum",
  "oena.": "Oenanthe crocata",
  "olnd.": "Oleander",
  "ol-an.": "Oleum animale",
  "ol-j.": "Oleum jecoris aselli",
  "onos.": "Onosmodium",
  "op.": "Opium",
  "orig.": "Origanum majorana",
  "osm.": "Osmium",
  "ov.": "Ovinine",
  "ox-ac.": "Oxalicum acidum",
  "oxyt.": "Oxytropis lamberti",
  "ozone": "Ozone (Oxygenium)",
  "paeon.": "Pæonia officinalis",
  "pall.": "Palladium",
  "pareir.": "Pareira brava",
  "par.": "Paris quadrifolia",
  "paull.": "Paullinja pinnata",
  "ped.": "Pediculus capitis",
  "pen.": "Penthorum",
  "penic.": "Penicillinum",
  "per.": "Persica",
  "peti.": "Petiveria",
  "petr.": "Petroleum",
  "petros.": "Petroselinum",
  "phal.": "Phallus impudicus",
  "phase.": "Phaseolus nanus",
  "phel.": "Phellandrium",
  "ph-ac.": "Phosphoricum acidum",
  "phos.": "Phosphorus",
  "phys.": "Physostigma",
  "phyt.": "Phytolacca decandra",
  "pic-ac.": "Picricum acidum",
  "pimp.": "Pimpinella saxifraga",
  "pin-s.": "Pinus silvestris",
  "pip-m.": "Piper methysticum",
  "pip-n.": "Piper nigrum",
  "plan.": "Plantago major",
  "plat.": "Platinum metallicum",
  "plat-m.": "Platinum muriaticum",
  "pled.": "Plectranthus",
  "plumbg.": "Plumbago littoralis",
  "plb.": "Plumbum metallicum",
  "plb-acet.": "plumbum aceticum",
  "podo.": "Podophyllum peltatum",
  "polyg.": "Polygonum hydropiperoides",
  "polyp-o.": "Polyporous Officinalis",
  "pop.": "Populus tremuloides",
  "poth.": "Pothos fœtidus",
  "prun.": "Prunus spinosa",
  "psor.": "Psorinum",
  "ptel.": "Ptelea trifoliata",
  "pulx.": "Pulex iritans",
  "puls.": "Pulsatilla nigricans",
  "pul-n.": "Pulsatilla nuttaliana",
  "pyrog.": "Pyrogenium",
  "pyrus.": "Pyrus americana",
  "querc-g-sp.": "Quercus glandis spiritus",
  "rad.": "Radium",
  "ran-a.": "Ranunculus acris",
  "ran-b.": "Ranunculus bulbosus",
  "ran-s.": "Ranunculus sceleratus",
  "raph.": "Raphanus",
  "rat.": "Ratanhia",
  "rheum": "Rheum",
  "rhod.": "Rhododendron",
  "rhus-a.": "Rhus aromatica",
  "rhus-g.": "Rhus glabra",
  "rhus-r.": "Rhus radicans",
  "rhus-t.": "Rhus toxicodendron",
  "rhus-v.": "Rhus venenata",
  "ric.": "Ricinus Communis",
  "rob.": "Robinia pseudacacia",
  "rubia-t.": "rubia tinctoria",
  "rumex.": "Rumex crispus",
  "ruta.": "Ruta graveolens",
  "sabad.": "Sabadilla",
  "sabal.": "Sabal serrulata",
  "sabin.": "Sabina",
  "sacc.": "Saccharum album",
  "sac-l.": "Saccharum lactis",
  "sal-ac.": "Salicylicum acidum",
  "salam.": "Salamander",
  "sal-n.": "Salix niger",
  "samb.": "Sambucus nigra",
  "sang.": "Sanguinaria canadensis",
  "sang-n.": "Sanguinaria nitrica",
  "sanic.": "Sanicula aqua",
  "sant.": "Santoninum",
  "sarr.": "Sarracenia purpurea",
  "sars.": "Sarsaparilla",
  "scirr.": "Scirrhinum",
  "scut.": "Scutellaria lateriflora",
  "sec.": "Secale cornutum",
  "sel.": "Selenium",
  "senec.": "Senecio aureus",
  "seneg.": "Senega",
  "senn.": "Senna",
  "sep.": "Sepia",
  "serp.": "Serpentaria",
  "sil.": "Sil.,Bac., -Abdomen, DISTENDED:In thin, rickety children, Sil. 6, 6h. Intercurrently, Bac. 30, once a week.",
  "sin-a.": "Sinapis alba",
  "sin-n.": "Sinapis nigra",
  "sol-m.": "Solanum mammosum",
  "sol-n.": "Solanum nigrum",
  "sol-o.": "Solanum oleraceum",
  "sol-t-ae.": "Solanum tuberosum aegrotans",
  "sol-v.": "Solidago v.a.",
  "spig.": "Spigelia anthelmia",
  "spig-m.": "Spigelia marilandica",
  "spira.": "Spiranthes",
  "spong.": "Spongia tosta",
  "squil.": "Squilla hispanica",
  "stach.": "Stachys betonica",
  "stann.": "Stannum metallicum",
  "staph.": "Staphysagria",
  "stel.": "Stellaria media",
  "stict.": "Sticta pulmonaria",
  "still.": "Stillingia sylvatica",
  "stram.": "Stramonium",
  "stront-c.": "Strontium carbonicum",
  "stroph.": "Strophanthus hispidus",
  "stry.": "Strychninum",
  "sulph.": "Sulphur",
  "sul-i.": "Sulphur iodatum",
  "sul-ac.": "Sulphuricum acidum",
  "sumb.": "Sumbul",
  "syph.": "Syphilinum",
  "symph.": "Symphytum officinale",
  "sym-r.": "Symphoricarpus racemosus",
  "tab.": "Tabacum",
  "tam-c.": "Tamus communis",
  "tanac.": "Tanacetum vulgare",
  "tann.": "Tanninum",
  "tarax.": "Taraxacum",
  "tarent.": "Tarentula hispanica",
  "tarent-c.": "Tarentula cubensis",
  "tart-ac.": "Tartaricum acid",
  "tax.": "Taxus baccata",
  "tell.": "Tellurium",
  "tep.": "Teplitz",
  "ter.": "Terebinthina",
  "teucr.": "Teucrium marum verum",
  "thal.": "Thallium",
  "thea": "Thea sinensis",
  "ther.": "Theridion",
  "thios.": "Thiosinaminum",
  "thlaspi.": "Thlaspi bursa pastoris",
  "thy.": "thyroidinum",
  "thuj.": " thuj., -Abdomen, DISTENDED:As if a living animal were there, Thuj. 12, 2h.",
  "til.": "Tilia curopea",
  "tong.": "Tongo",
  "trif-p.": "Trifolium pratense",
  "tril.": "Trillium pendulum",
  "trom.": "Trombidium muscæ domesticæ",
  "trio.": "Triosteum perfoliatum",
  "tub.": "Tuberculinum",
  "tub-av.": "Tuberculinum aviare",
  "tus-f.": "Tussilago fragrans",
  "tus-p.": "Tussilago petasites",
  "upa.": "Upas tiente",
  "uran.": "Uranium nitricum",
  "urt-u.": "Urtica urens",
  "ust.": "Ustilago maydis",
  "uva.": "Uva ursi",
  "vac.": "Vaccininum",
  "vanad.": "Vanadium",
  "valer.": "Valeriana",
  "vario.": "Variolinum",
  "verat.": "Veratrum album",
  "verat-v.": "Veratrum viride",
  "verb.": "Verbascum thapsus",
  "vesp.": "Vespa crabro",
  "vib.": "Viburnum opulus",
  "vinc.": "Vinca minor",
  "viol-o.": "Viola odorata",
  "viol-t.": "Viola tricolor",
  "vip.": "Vipera",
  "visc.": "Viscum alburn",
  "wies.": "Wiesbaden",
  "wild.": "Wildbad",
  "wye.": "Wyethia helenioides",
  "xan.": "Xanthoxylum fraxineum",
  "x-ray.": "X Ray",
  "yuc.": "Yucca",
  "zinc.": "Zincum metallicum",
  "zinc-ac.": "Zincum aceticum",
  "zinc-c.": "Zincum cyanatum",
  "zinc-m.": "Zincum muriaticum",
  "zinc-ox.": "Zincum oxydatum",
  "zinc-pic.": "Zincum Picricum",
  "zinc-s.": "Zincum sulphuricum",
  "zing.": "Zingiber",
  "ziz.": "Zizia aurea",
}

export const KENT_REPERTORY: KentRepertory = {
  bookName: "Kent Repertory",
  chapters: [
    {
      id: "mind",
      name: "Mind",
      icon: "🧠",
      description: "Mental and emotional symptoms",
      rubrics: [
        {
          id: "abandoned",
          name: "Abandoned",
          remedies: [],
          meaning: "",
          notes: [],
          crossReferences: [{ chapter: "Mind", rubric: "Forsaken feeling" }],
        },
        {
          id: "abrupt",
          name: "Abrupt",
          remedies: [
            { abbr: "nat-m.", grade: 1 },
            { abbr: "tarent.", grade: 2 },
          ],
          meaning: "Sudden & Unexpected Behaviour of the patient",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "Patient Suddenly enters the room without knocking or he/she may keep reports on your desk suddenly in a rough manner." },
            { type: "system", source: "Oza, Pt-Ver", text: "Patient may suddenly change topic while speaking to something else and it may look like loquacity but he/ she can have trait of abruptness." },
            { type: "system", source: "KR, WhenToUse", text: "You can observe the behaviour of the patient when entering the clinic or while case taking to take this rubric for repertorisation.The behaviour of the patient is very sudden or harsh.Example - banging the door, coming inside the clinic and suddenly starting to tell about his complaints without any background of himself" },
            { type: "system", source: "KR, WhenToUseMetaphor", text: "Abruptness indicates a sudden shift in behaviour or act or break in continuity of talk or action implying taking this rubric in analysis" },
          ],
          crossReferences: [{ chapter: "Mind", rubric: "Answers; abruptly" }],
        },
        {
          id: "absent-minded",
          name: "Absent-minded",
          remedies: [
            { abbr: "acon.", grade: 2 }, { abbr: "act-sp.", grade: 1 }, { abbr: "aesc.", grade: 1 }, { abbr: "agar.", grade: 1 }, { abbr: "agn.", grade: 2 }, { abbr: "all-c.", grade: 1 }, { abbr: "alum.", grade: 2 }, { abbr: "am-c.", grade: 2 }, { abbr: "am-m.", grade: 1 }, { abbr: "anac.", grade: 2 }, { abbr: "ang.", grade: 1 }, { abbr: "apis", grade: 3 }, { abbr: "arg.", grade: 1 }, { abbr: "arn.", grade: 2 }, { abbr: "ars.", grade: 1 }, { abbr: "arum-t.", grade: 1 }, { abbr: "asar.", grade: 1 }, { abbr: "aur.", grade: 2 }, { abbr: "bar-c.", grade: 2 }, { abbr: "bell.", grade: 2 }, { abbr: "bov.", grade: 2 }, { abbr: "bufo", grade: 2 }, { abbr: "calad.", grade: 2 }, { abbr: "calc.", grade: 1 }, { abbr: "calc-s.", grade: 1 }, { abbr: "cann-i.", grade: 3 }, { abbr: "cann-s.", grade: 1 }, { abbr: "caps.", grade: 1 }, { abbr: "carb-ac.", grade: 1 }, { abbr: "carb-s.", grade: 1 }, { abbr: "carl.", grade: 2 }, { abbr: "caust.", grade: 3 }, { abbr: "cench.", grade: 1 }, { abbr: "cham.", grade: 3 }, { abbr: "chel.", grade: 1 }, { abbr: "chin.", grade: 1 }, { abbr: "cic.", grade: 2 }, { abbr: "clem.", grade: 1 }, { abbr: "cocc.", grade: 2 }, { abbr: "coff.", grade: 1 }, { abbr: "colch.", grade: 2 }, { abbr: "coloc.", grade: 1 }, { abbr: "con.", grade: 1 }, { abbr: "croc.", grade: 1 }, { abbr: "crot-h.", grade: 1 }, { abbr: "cupr.", grade: 2 }, { abbr: "cycl.", grade: 1 }, { abbr: "daph.", grade: 1 }, { abbr: "dirc.", grade: 1 }, { abbr: "dulc.", grade: 1 }, { abbr: "elaps", grade: 1 }, { abbr: "graph.", grade: 2 }, { abbr: "guai.", grade: 1 }, { abbr: "ham.", grade: 1 }, { abbr: "hell.", grade: 3 }, { abbr: "hep.", grade: 1 }, { abbr: "hura", grade: 1 }, { abbr: "hyos.", grade: 2 }, { abbr: "ign.", grade: 2 }, { abbr: "jug-c.", grade: 1 }, { abbr: "kali-br.", grade: 2 }, { abbr: "kali-c.", grade: 2 }, { abbr: "kali-p.", grade: 2 }, { abbr: "kali-s.", grade: 1 }, { abbr: "kreos.", grade: 2 }, { abbr: "lac-c.", grade: 2 }, { abbr: "lach.", grade: 3 }, { abbr: "led.", grade: 1 }, { abbr: "lyc.", grade: 2 }, { abbr: "lyss.", grade: 1 }, { abbr: "mag-c.", grade: 2 }, { abbr: "manc.", grade: 1 }, { abbr: "mang.", grade: 1 }, { abbr: "merc.", grade: 2 }, { abbr: "mez.", grade: 3 }, { abbr: "mosch.", grade: 2 }, { abbr: "naja", grade: 1 }, { abbr: "nat-c.", grade: 1 }, { abbr: "nat-m.", grade: 3 }, { abbr: "nat-p.", grade: 1 }, { abbr: "nit-ac.", grade: 1 }, { abbr: "nux-m.", grade: 3 }, { abbr: "nux-v.", grade: 2 }, { abbr: "olnd.", grade: 2 }, { abbr: "onos.", grade: 2 }, { abbr: "op.", grade: 2 }, { abbr: "petr.", grade: 2 }, { abbr: "ph-ac.", grade: 2 }, { abbr: "phos.", grade: 2 }, { abbr: "plat.", grade: 3 }, { abbr: "plb.", grade: 2 }, { abbr: "puls.", grade: 3 }, { abbr: "rhod.", grade: 1 }, { abbr: "rhus-t.", grade: 2 }, { abbr: "rhus-v.", grade: 1 }, { abbr: "ruta", grade: 1 }, { abbr: "sars.", grade: 1 }, { abbr: "sep.", grade: 3 }, { abbr: "sil.", grade: 2 }, { abbr: "spong.", grade: 1 }, { abbr: "stann.", grade: 1 }, { abbr: "stram.", grade: 1 }, { abbr: "sul-ac.", grade: 1 }, { abbr: "sulph.", grade: 2 }, { abbr: "tarent.", grade: 1 }, { abbr: "thuj.", grade: 1 }, { abbr: "verat.", grade: 3 }, { abbr: "verb.", grade: 1 }, { abbr: "viol-o.", grade: 1 }, { abbr: "viol-t.", grade: 1 }, { abbr: "zinc.", grade: 1 }
          ],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "In Case taking, Patient may not go into absentmindedness since he has come to you for healing and may be aware of his action or speech. Hence it is best to take examples from patient about this behaviour. He/she may tell you that at times he/she was travelling in bus and he forgot his umbrella there." },
            { type: "system", source: "Oza, Pt-Ver", text: "Dr I feel i keep forgetting things some times especially when i m thinking about some other topic" },
            { type: "system", source: "KR, WhenToUse", text: "It may not be clearly evident in Case taking if patient is well aware of his speech and actions or in compensated cases. Hence it is best to understand the absentmindedness from examples given by patient about daily life to life activities or examples from relatives." },
            { type: "system", source: "KR, WhenToUseMetaphor", text: "Absentmindedness is often a picture of someone who is lost in thought or is away from the present moment. any act showing patient is occupied in something else rather than the current conversation or the present moment, shall be a guide to take this rubric for analysis" },
          ],
          crossReferences: [{ chapter: "Mind", rubric: "Forgetful" }],
        },
        {
          id: "absent-minded-morning",
          name: "Absent-minded; morning",
          remedies: [
            { abbr: "guai.", grade: 1 }, { abbr: "nat-c.", grade: 1 }, { abbr: "ph-ac.", grade: 1 }, { abbr: "phos.", grade: 1 }
          ],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absent-minded-11am-4pm",
          name: "Absent-minded; 11 a.m. to 4 p.m.",
          remedies: [{ abbr: "kali-n.", grade: 1 }],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absent-minded-noon",
          name: "Absent-minded; noon",
          remedies: [{ abbr: "mosch.", grade: 1 }],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absent-minded-menses-during",
          name: "Absent-minded; menses, during",
          remedies: [{ abbr: "calc.", grade: 1 }],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absent-minded-periodical-attacks-of-short-lasting",
          name: "Absent-minded; periodical attacks of, short lasting",
          remedies: [{ abbr: "fl-ac.", grade: 1 }, { abbr: "nux-m.", grade: 2 }],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absent-minded-reading-while",
          name: "Absent-minded; reading, while",
          remedies: [
            { abbr: "agn.", grade: 1 }, { abbr: "lach.", grade: 1 }, { abbr: "nux-m.", grade: 2 }, { abbr: "ph-ac.", grade: 1 }
          ],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absent-minded-starts-when-spoken-to",
          name: "Absent-minded; starts when spoken to",
          remedies: [{ abbr: "carb-ac.", grade: 1 }],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absent-minded-writing-while",
          name: "Absent-minded; writing, while",
          remedies: [{ abbr: "mag-c.", grade: 1 }],
          meaning: "Absentmindedness simply means having or showing forgetful or inattentive behaviour.",
          notes: [],
        },
        {
          id: "absorbed",
          name: "Absorbed",
          remedies: [
            { abbr: "acon.", grade: 1 }, { abbr: "aloe", grade: 1 }, { abbr: "am-m.", grade: 1 }, { abbr: "ant-c.", grade: 1 }, { abbr: "arn.", grade: 2 }, { abbr: "bell.", grade: 1 }, { abbr: "bov.", grade: 1 }, { abbr: "calc.", grade: 1 }, { abbr: "cann-i.", grade: 1 }, { abbr: "canth.", grade: 1 }, { abbr: "caps.", grade: 2 }, { abbr: "carl.", grade: 2 }, { abbr: "caust.", grade: 1 }, { abbr: "cham.", grade: 1 }, { abbr: "chin.", grade: 1 }, { abbr: "cic.", grade: 1 }, { abbr: "clem.", grade: 1 }, { abbr: "cocc.", grade: 2 }, { abbr: "con.", grade: 1 }, { abbr: "cupr.", grade: 1 }, { abbr: "cycl.", grade: 1 }, { abbr: "elaps", grade: 1 }, { abbr: "grat.", grade: 1 }, { abbr: "ham.", grade: 1 }, { abbr: "hell.", grade: 3 }, { abbr: "ign.", grade: 1 }, { abbr: "ip.", grade: 1 }, { abbr: "lil-t.", grade: 1 }, { abbr: "mang.", grade: 1 }, { abbr: "merc.", grade: 1 }, { abbr: "mez.", grade: 3 }, { abbr: "mosch.", grade: 1 }, { abbr: "mur-ac.", grade: 1 }, { abbr: "nat-c.", grade: 1 }, { abbr: "nat-m.", grade: 2 }, { abbr: "nat-p.", grade: 1 }, { abbr: "nit-ac.", grade: 1 }, { abbr: "nux-m.", grade: 3 }, { abbr: "ol-an.", grade: 1 }, { abbr: "onos.", grade: 2 }, { abbr: "op.", grade: 2 }, { abbr: "phel.", grade: 1 }, { abbr: "phos.", grade: 1 }, { abbr: "puls.", grade: 2 }, { abbr: "rheum", grade: 1 }, { abbr: "sabad.", grade: 1 }, { abbr: "sars.", grade: 1 }, { abbr: "spig.", grade: 1 }, { abbr: "stann.", grade: 1 }, { abbr: "stram.", grade: 1 }, { abbr: "sulph.", grade: 3 }
          ],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "Sometimes you are engrossed in somework and you do not realise what is happening around you that is Absorbed. In Homeopathic Case Taking,patients will tell that at times when they are in stress they are occupied in one thought about the stress. This can be taken as Absorbed. Although Do refer the cross references as suggestions from us" },
            { type: "system", source: "Oza, Pt-Ver", text: "The relatives will tell you that the paitient is inattentive to our talks at times and is in his/her own world. The patient is overly concerned with himself, including his/her own feelings and thoughts (health related or other thoughts) without any attention for outside world" },
            { type: "system", source: "KR, WhenToUse", text: "You can use this rubric in all patients who have been described in patient versions by us. And also in cases of Functional cases of Psychiatric illnesses especially Personality Disorders and Brain injuries." },
          ],
        },
        {
          id: "absorbed-daytime",
          name: "Absorbed; daytime",
          remedies: [{ abbr: "elaps", grade: 1 }],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "The relatives will tell you that the paitient is inattentive to our talks at times and is in his/her own world. The patient is overly concerned with himself, including his/her own feelings and thoughts (health related or other thoughts) without any attention for outside world" },
          ],
        },
        {
          id: "absorbed-morning",
          name: "Absorbed; morning",
          remedies: [{ abbr: "nat-c.", grade: 2 }, { abbr: "nux-v.", grade: 1 }],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "The relatives will tell you that the paitient is inattentive to our talks at times and is in his/her own world. The patient is overly concerned with himself, including his/her own feelings and thoughts (health related or other thoughts) without any attention for outside world" },
          ],
        },
        {
          id: "absorbed-afternoon",
          name: "Absorbed; afternoon",
          remedies: [{ abbr: "mang.", grade: 1 }],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "The relatives will tell you that the paitient is inattentive to our talks at times and is in his/her own world. The patient is overly concerned with himself, including his/her own feelings and thoughts (health related or other thoughts) without any attention for outside world" },
          ],
        },
        {
          id: "absorbed-evening",
          name: "Absorbed; evening",
          remedies: [{ abbr: "am-m.", grade: 1 }, { abbr: "sulph", grade: 2 }],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "The relatives will tell you that the paitient is inattentive to our talks at times and is in his/her own world. The patient is overly concerned with himself, including his/her own feelings and thoughts (health related or other thoughts) without any attention for outside world" },
          ],
        },
        {
          id: "absorbed-alternating-with-frivolity",
          name: "Absorbed; alternating, with frivolity",
          remedies: [{ abbr: "arg-n.", grade: 1 }],
          meaning: "Absorbed means something or someone that is taking the attention totally, Frivolity means taking for granted or not serious in doing something",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "The relatives will tell you that the paitient is inattentive to our talks at times and is in his/her own world. The patient is overly concerned with himself, including his/her own feelings and thoughts (health related or other thoughts) without any attention for outside world" },
          ],
        },
        {
          id: "absorbed-as-to-what-would-become-of-him",
          name: "Absorbed; as to what would become of him",
          remedies: [{ abbr: "nat-m.", grade: 1 }],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "I m stressed at my current condition (financial,health,relationship) and worried as to what will happen to me in future or what will be my future if today things are not good" },
          ],
        },
        {
          id: "absorbed-eating-after",
          name: "Absorbed; eating, after",
          remedies: [{ abbr: "aloe.", grade: 1 }],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "After meals I am disinclined to talk" },
          ],
        },
        {
          id: "absorbed-menses-during",
          name: "Absorbed; menses, during",
          remedies: [{ abbr: "mur-ac.", grade: 1 }],
          meaning: "Absorbed means something or someone that is taking the attention totally",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "During My Menses, I am more in my own world. At times i do not respond to my relatives' responses" },
            { type: "system", source: "Oza, Pt-Ver", text: "The patient is in own world during menses. She does not talk or react for sometime with us..and we need to ask multiple times." },
          ],
        },
        {
          id: "abstraction-of-mind",
          name: "Abstraction of mind",
          remedies: [
            { abbr: "alum.", grade: 1 }, { abbr: "aml-n.", grade: 1 }, { abbr: "camph.", grade: 1 }, { abbr: "cann-i.", grade: 2 }, { abbr: "carb-ac.", grade: 1 }, { abbr: "caust.", grade: 1 }, { abbr: "cic.", grade: 1 }, { abbr: "con.", grade: 1 }, { abbr: "cycl.", grade: 1 }, { abbr: "elaps", grade: 1 }, { abbr: "guai.", grade: 1 }, { abbr: "hell.", grade: 2 }, { abbr: "hyos.", grade: 2 }, { abbr: "kreos.", grade: 2 }, { abbr: "laur.", grade: 1 }, { abbr: "lyc.", grade: 1 }, { abbr: "lyss.", grade: 1 }, { abbr: "mez.", grade: 1 }, { abbr: "nat-m.", grade: 2 }, { abbr: "nux-m.", grade: 3 }, { abbr: "oena.", grade: 2 }, { abbr: "onos.", grade: 2 }, { abbr: "op.", grade: 1 }, { abbr: "ph-ac.", grade: 1 }, { abbr: "phos.", grade: 3 }, { abbr: "plat.", grade: 1 }, { abbr: "sabad.", grade: 1 }, { abbr: "sec.", grade: 1 }, { abbr: "sil.", grade: 1 }, { abbr: "stram.", grade: 1 }, { abbr: "sulph.", grade: 2 }, { abbr: "vesp.", grade: 1 }, { abbr: "visc.", grade: 2 }
          ],
          meaning: "Abstract comes from a Latin word meaning pulled away, detached, and the basic idea is of something detached from physical, or concrete, reality.",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "The relatives may tell you - the patient is not so much connected to us these days in terms of communication" },
          ],
        },
        {
          id: "abstraction-of-mind-morning",
          name: "Abstraction of mind; morning",
          remedies: [{ abbr: "guai.", grade: 1 }],
          meaning: "",
          notes: [],
        },
        {
          id: "absurd",
          name: "Absurd",
          remedies: [],
          meaning: "",
          notes: [],
        },
        {
          id: "abusive",
          name: "Abusive",
          remedies: [
            { abbr: "am-c.", grade: 1 }, { abbr: "am-m.", grade: 1 }, { abbr: "anac.", grade: 2 }, { abbr: "bell.", grade: 2 }, { abbr: "borx.", grade: 1 }, { abbr: "caust.", grade: 1 }, { abbr: "con.", grade: 1 }, { abbr: "dulc.", grade: 1 }, { abbr: "hyos.", grade: 2 }, { abbr: "ip.", grade: 1 }, { abbr: "lyc.", grade: 1 }, { abbr: "lyss.", grade: 2 }, { abbr: "mosch.", grade: 1 }, { abbr: "petr.", grade: 2 }, { abbr: "plb.", grade: 1 }, { abbr: "ran-b.", grade: 1 }, { abbr: "seneg.", grade: 2 }, { abbr: "sep.", grade: 2 }, { abbr: "spong.", grade: 1 }, { abbr: "stram.", grade: 1 }, { abbr: "verat.", grade: 2 }, { abbr: "viol-t.", grade: 1 }
          ],
          meaning: "Abusive means to treate someone with cruelty or violence repeatedly or recurrently",
          notes: [
            { type: "system", source: "Oza, Pt-Ver", text: "Not always will the patient share his negative traits so we can get to know from the relatives that the patient is abusive in home - uses very bad words in talking or even curses at times." },
          ],
        },
      ],
    },
    {
      id: "vertigo",
      name: "Vertigo",
      icon: "💫",
      description: "Symptoms related to dizziness and balance",
      rubrics: [
        {
          id: "vertigo-general",
          name: "Vertigo in general",
          remedies: [
            { abbr: "acon.", grade: 2 },
            { abbr: "bell.", grade: 2 },
            { abbr: "bry.", grade: 3 },
            { abbr: "calc.", grade: 2 },
            { abbr: "chin.", grade: 2 },
            { abbr: "con.", grade: 3 },
            { abbr: "gels.", grade: 2 },
            { abbr: "nux-v.", grade: 2 },
            { abbr: "phos.", grade: 2 },
            { abbr: "puls.", grade: 2 },
            { abbr: "sil.", grade: 2 },
            { abbr: "sulph.", grade: 2 },
          ],
          meaning:
            "Sensation of spinning or loss of balance. May be accompanied by nausea, unsteadiness, or disorientation.",
          notes: [
            {
              type: "system",
              source: "KR, WhenToUse",
              text: "Consider modalities - when the vertigo occurs, what makes it better or worse.",
            },
          ],
          crossReferences: [
            { chapter: "Head", rubric: "Heaviness" },
            { chapter: "Stomach", rubric: "Nausea" },
          ],
        },
      ],
    },
    {
      id: "head",
      name: "Head",
      icon: "🗣️",
      description: "Symptoms of the head excluding the mind",
      rubrics: [
        {
          id: "headache",
          name: "Pain, headache in general",
          remedies: [
            { abbr: "acon.", grade: 2 },
            { abbr: "bell.", grade: 3 },
            { abbr: "bry.", grade: 3 },
            { abbr: "calc.", grade: 2 },
            { abbr: "chin.", grade: 2 },
            { abbr: "gels.", grade: 3 },
            { abbr: "glon.", grade: 3 },
            { abbr: "ign.", grade: 2 },
            { abbr: "lach.", grade: 2 },
            { abbr: "lyc.", grade: 2 },
            { abbr: "nat-m.", grade: 3 },
            { abbr: "nux-v.", grade: 3 },
            { abbr: "phos.", grade: 2 },
            { abbr: "puls.", grade: 2 },
            { abbr: "sep.", grade: 2 },
            { abbr: "sil.", grade: 3 },
            { abbr: "spig.", grade: 3 },
            { abbr: "sulph.", grade: 2 },
          ],
          meaning:
            "Pain in any part of the head. May vary in character, location, and modalities.",
          notes: [
            {
              type: "system",
              source: "KR, WhenToUse",
              text: "Note the exact location, character of pain (throbbing, pressing, etc.), and what makes it better or worse.",
            },
          ],
          crossReferences: [
            { chapter: "Head", rubric: "Congestion" },
            { chapter: "Eye", rubric: "Pain" },
          ],
        },
      ],
    },
    { id: "eye", name: "Eye", icon: "👁️", description: "Symptoms related to the eyes and vision", rubrics: [] },
    { id: "vision", name: "Vision", icon: "👓", description: "Visual disturbances and symptoms", rubrics: [] },
    { id: "ear", name: "Ear", icon: "👂", description: "Symptoms of the ear", rubrics: [] },
    { id: "hearing", name: "Hearing", icon: "🔊", description: "Hearing-related symptoms", rubrics: [] },
    { id: "nose", name: "Nose", icon: "👃", description: "Symptoms of the nose", rubrics: [] },
    { id: "face", name: "Face", icon: "😶", description: "Symptoms of the face", rubrics: [] },
    { id: "mouth", name: "Mouth", icon: "👄", description: "Symptoms of the mouth", rubrics: [] },
    { id: "teeth", name: "Teeth", icon: "🦷", description: "Dental symptoms", rubrics: [] },
    { id: "throat", name: "Throat", icon: "🔴", description: "Throat symptoms", rubrics: [] },
    { id: "external-throat", name: "External Throat", icon: "🔵", description: "External throat symptoms", rubrics: [] },
    { id: "stomach", name: "Stomach", icon: "🫃", description: "Stomach symptoms", rubrics: [] },
    { id: "abdomen", name: "Abdomen", icon: "🫄", description: "Abdominal symptoms", rubrics: [] },
    { id: "rectum", name: "Rectum", icon: "🔶", description: "Rectal symptoms", rubrics: [] },
    { id: "stool", name: "Stool", icon: "🟤", description: "Stool characteristics", rubrics: [] },
    { id: "bladder", name: "Bladder", icon: "💧", description: "Bladder symptoms", rubrics: [] },
    { id: "kidneys", name: "Kidneys", icon: "🫘", description: "Kidney symptoms", rubrics: [] },
    { id: "prostate", name: "Prostate Gland", icon: "🔘", description: "Prostate symptoms", rubrics: [] },
    { id: "urethra", name: "Urethra", icon: "💦", description: "Urethral symptoms", rubrics: [] },
    { id: "urine", name: "Urine", icon: "🧪", description: "Urine characteristics", rubrics: [] },
    { id: "genitalia-male", name: "Genitalia Male", icon: "♂️", description: "Male genital symptoms", rubrics: [] },
    { id: "genitalia-female", name: "Genitalia Female", icon: "♀️", description: "Female genital symptoms", rubrics: [] },
    { id: "larynx", name: "Larynx & Trachea", icon: "🎤", description: "Larynx and trachea symptoms", rubrics: [] },
    { id: "respiration", name: "Respiration", icon: "🌬️", description: "Breathing symptoms", rubrics: [] },
    { id: "cough", name: "Cough", icon: "🤧", description: "Cough symptoms", rubrics: [] },
    { id: "expectoration", name: "Expectoration", icon: "💨", description: "Expectoration symptoms", rubrics: [] },
    { id: "chest", name: "Chest", icon: "🫁", description: "Chest symptoms", rubrics: [] },
    { id: "back", name: "Back", icon: "🔙", description: "Back symptoms", rubrics: [] },
    { id: "extremities", name: "Extremities", icon: "🦵", description: "Symptoms of limbs", rubrics: [] },
    { id: "sleep", name: "Sleep", icon: "😴", description: "Sleep-related symptoms", rubrics: [] },
    { id: "dreams", name: "Dreams", icon: "💭", description: "Dream patterns", rubrics: [] },
    { id: "chill", name: "Chill", icon: "🥶", description: "Chilliness symptoms", rubrics: [] },
    { id: "fever", name: "Fever", icon: "🤒", description: "Fever symptoms", rubrics: [] },
    { id: "perspiration", name: "Perspiration", icon: "💦", description: "Sweating symptoms", rubrics: [] },
    { id: "skin", name: "Skin", icon: "🖐️", description: "Skin symptoms", rubrics: [] },
    { id: "generalities", name: "Generalities", icon: "⚡", description: "General symptoms affecting the whole person", rubrics: [] },
  ],
}

export const CLINICAL_REPERTORY: KentRepertory = {
  bookName: "Clinical",
  chapters: [
    {
      id: "clinical-abdomen",
      name: "Clinical – Abdomen & Abscess",
      icon: "⚕️",
      description: "Clinical rubrics from Clarke and Boericke for abdomen and abscess",
      rubrics: [
        {
          id: "abdomen-coldness-in-clarke",
          name: "Abdomen; Coldness in (Clarke)",
          remedies: [
            { abbr: "phel.", grade: 1 },
            { abbr: "plect.", grade: 1 },
          ],
          meaning: "Testing",
          notes: [
            { type: "system", source: "HCP", text: "Testing" },
            { type: "system", source: "HCP", text: "IX to do" },
            { type: "system", source: "Clarke", text: "TESTING" },
          ],
          crossReferences: [],
        },
        {
          id: "abdomen-coldness-in-boericke",
          name: "Abdomen; Coldness in (Boericke)",
          remedies: [
            { abbr: "aeth.", grade: 1 },
            { abbr: "ambr.", grade: 1 },
            { abbr: "bar-c.", grade: 1 },
            { abbr: "cadm-s.", grade: 1 },
            { abbr: "chin.", grade: 1 },
            { abbr: "colch.", grade: 1 },
            { abbr: "dulc.", grade: 1 },
            { abbr: "kali-br.", grade: 1 },
            { abbr: "kali-c.", grade: 1 },
            { abbr: "kali-s.", grade: 1 },
            { abbr: "meny.", grade: 1 },
            { abbr: "onos.", grade: 1 },
            { abbr: "phos.", grade: 1 },
            { abbr: "sil.", grade: 1 },
            { abbr: "staph.", grade: 1 },
            { abbr: "tab.", grade: 1 },
            { abbr: "verat.", grade: 1 },
          ],
          meaning: "Testing",
          notes: [
            { type: "system", source: "HCP", text: "Testing" },
            { type: "system", source: "HCP", text: "IX to do" },
            { type: "system", source: "Boericke", text: "TESTING" },
          ],
          crossReferences: [],
        },
        {
          id: "abdomen-distended-clarke",
          name: "Abdomen; Distended (Clarke)",
          remedies: [
            { abbr: "calc.", grade: 1 },
            { abbr: "dios.", grade: 1 },
            { abbr: "cin.", grade: 1 },
            { abbr: "ign.", grade: 1 },
            { abbr: "lyc.", grade: 1 },
            { abbr: "sil.", grade: 1 },
            { abbr: "thuj.", grade: 1 },
          ],
          meaning: "Testing",
          notes: [
            { type: "system", source: "HCP", text: "Testing" },
            { type: "system", source: "HCP", text: "Testing" },
          ],
          crossReferences: [],
        },
        {
          id: "abdomen-distended-boericke",
          name: "Abdomen; Distended (Boericke)",
          remedies: [
            { abbr: "abies-c.", grade: 1 },
            { abbr: "abrot.", grade: 1 },
            { abbr: "acal.", grade: 1 },
            { abbr: "act-sp.", grade: 1 },
            { abbr: "agar.", grade: 1 },
            { abbr: "ambr.", grade: 1 },
            { abbr: "anthro.", grade: 1 },
            { abbr: "aran.", grade: 1 },
            { abbr: "arg-n.", grade: 1 },
            { abbr: "arn.", grade: 1 },
            { abbr: "bapt.", grade: 1 },
            { abbr: "bar-c.", grade: 1 },
            { abbr: "bell.", grade: 1 },
            { abbr: "brom.", grade: 1 },
            { abbr: "caj.", grade: 1 },
            { abbr: "calc.", grade: 1 },
            { abbr: "cann-i.", grade: 1 },
            { abbr: "carb-ac.", grade: 1 },
            { abbr: "carb-v.", grade: 1 },
            { abbr: "carb-s.", grade: 1 },
            { abbr: "cham.", grade: 1 },
            { abbr: "chel.", grade: 1 },
            { abbr: "chin.", grade: 1 },
            { abbr: "cic.", grade: 1 },
            { abbr: "coca", grade: 1 },
            { abbr: "cocc.", grade: 1 },
            { abbr: "colch.", grade: 1 },
            { abbr: "coloc.", grade: 1 },
            { abbr: "corn.", grade: 1 },
            { abbr: "crot-h.", grade: 1 },
            { abbr: "gamb.", grade: 1 },
            { abbr: "hedeom.", grade: 1 },
            { abbr: "hep.", grade: 1 },
            { abbr: "hyos.", grade: 1 },
            { abbr: "iodof.", grade: 1 },
            { abbr: "jal.", grade: 1 },
            { abbr: "jatr.", grade: 1 },
            { abbr: "jug-r.", grade: 1 },
            { abbr: "kali-c.", grade: 1 },
            { abbr: "kreos.", grade: 1 },
            { abbr: "lil-t.", grade: 1 },
            { abbr: "meny.", grade: 1 },
            { abbr: "merc.", grade: 1 },
            { abbr: "morph.", grade: 1 },
            { abbr: "mosch.", grade: 1 },
            { abbr: "nat-m.", grade: 1 },
            { abbr: "nat-n.", grade: 1 },
            { abbr: "nux-m.", grade: 1 },
            { abbr: "nux-v.", grade: 1 },
            { abbr: "onos.", grade: 1 },
            { abbr: "ph-ac.", grade: 1 },
            { abbr: "podo.", grade: 1 },
            { abbr: "puls.", grade: 1 },
            { abbr: "raph.", grade: 1 },
            { abbr: "rhus-t.", grade: 1 },
            { abbr: "sabin.", grade: 1 },
            { abbr: "scut.", grade: 1 },
            { abbr: "sil.", grade: 1 },
            { abbr: "sumb.", grade: 1 },
            { abbr: "tab.", grade: 1 },
            { abbr: "ter.", grade: 1 },
            { abbr: "thuj.", grade: 1 },
            { abbr: "zinc.", grade: 1 },
          ],
          meaning:
            "Distended abdomen can result from various factors, including gas accumulation, fluid retention, digestive disorders, and more serious medical conditions.",
          notes: [
            { type: "system", source: "HCP", text: "Testing" },
          ],
          crossReferences: [],
        },
        {
          id: "abdomen-large-clarke",
          name: "Abdomen; Large (Clarke)",
          remedies: [{ abbr: "calc.", grade: 1 }],
          meaning: "Testing",
          notes: [{ type: "system", source: "HCP", text: "Testing" }],
          crossReferences: [],
        },
        {
          id: "abdomen-large-boericke",
          name: "Abdomen; Large (Boericke)",
          remedies: [
            { abbr: "mez.", grade: 1 },
            { abbr: "phos.", grade: 1 },
            { abbr: "urt-u.", grade: 1 },
          ],
          meaning: "Testing",
          notes: [{ type: "system", source: "HCP", text: "Testing" }],
          crossReferences: [],
        },
        {
          id: "abdomen-operations-on-vomiting-after",
          name: "Abdomen; Operations on, vomiting after",
          remedies: [
            { abbr: "all-c.", grade: 1 },
            { abbr: "bism.", grade: 1 },
          ],
          meaning: "Testing",
          notes: [{ type: "system", source: "HCP", text: "Testing" }],
          crossReferences: [],
        },
        {
          id: "abdomen-plethora-of-clarke",
          name: "Abdomen; Plethora of (Clarke)",
          remedies: [{ abbr: "aloe.", grade: 1 }],
          meaning: "Testing",
          notes: [{ type: "system", source: "HCP", text: "Testing" }],
          crossReferences: [],
        },
        {
          id: "abdomen-plethora-of-boericke",
          name: "Abdomen; Plethora of (Boericke)",
          remedies: [{ abbr: "sulph.", grade: 1 }],
          meaning: "Testing",
          notes: [{ type: "system", source: "HCP", text: "Testing" }],
          crossReferences: [],
        },
        {
          id: "abdomen-swelling-of-clarke",
          name: "Abdomen; Swelling of (Clarke)",
          remedies: [{ abbr: "paraf.", grade: 1 }],
          meaning: "Dropsical swelling of abdomen (ascites).",
          notes: [{ type: "system", source: "HCP", text: "Testing" }],
          crossReferences: [],
        },
        {
          id: "abscess-clarke",
          name: "Abscess (Clarke)",
          remedies: [
            { abbr: "anan.", grade: 1 },
            { abbr: "apis.", grade: 1 },
            { abbr: "arn.", grade: 1 },
            { abbr: "ars.", grade: 1 },
            { abbr: "bell.", grade: 1 },
            { abbr: "calc-s.", grade: 1 },
            { abbr: "calen.", grade: 1 },
            { abbr: "chin.", grade: 1 },
            { abbr: "elat.", grade: 1 },
            { abbr: "fl-ac.", grade: 1 },
            { abbr: "guai.", grade: 1 },
            { abbr: "hep.", grade: 1 },
            { abbr: "hippoz.", grade: 1 },
            { abbr: "merc.", grade: 1 },
            { abbr: "nat-sal.", grade: 1 },
            { abbr: "pyrog.", grade: 1 },
            { abbr: "sil.", grade: 1 },
            { abbr: "symph.", grade: 1 },
            { abbr: "syph.", grade: 1 },
            { abbr: "thyr.", grade: 1 },
          ],
          meaning: "Testing",
          notes: [
            {
              type: "system",
              source: "Clarke",
              text:
                "Detailed clinical instructions for abscess and suppuration management; see Clarke's text for dosing and local applications.",
            },
          ],
          crossReferences: [],
        },
      ],
    },
  ],
}

// Unified library of all books for navigation
REPERTORY_BOOKS.push(KENT_REPERTORY, CLINICAL_REPERTORY)

export function getRemedyFullName(abbr: string): string {
  const cleanAbbr = abbr.toLowerCase().trim()
  return REMEDY_DICTIONARY[cleanAbbr] || abbr
}

export function formatRemedy(remedy: Remedy): string {
  const prefix = remedy.grade > 1 ? remedy.grade : ""
  return `${prefix}${remedy.abbr}`
}
